[package]
name = "library"
version = "0.1.0"
authors = ["cashew <42924021+cashev@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["parallel", "serde"]

special = []

parallel = ["crossbeam"]

nightly = ["crossbeam/nightly"]

full = ["crossbeam/nightly", "parallel", "serde"]

[dependencies]
crossbeam = {version = "0.7.3", optional = true}
serde = {version = "1.0.111", optional = true}
